/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uhc.schema.model.eligibility.cdb;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CdbTelephoneNumberReferenceData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6086107721206341518L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CdbTelephoneNumberReferenceData\",\"namespace\":\"com.uhc.schema.model.eligibility.cdb\",\"fields\":[{\"name\":\"telephoneTypeCode\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CdbTelephoneNumberReferenceData> ENCODER =
      new BinaryMessageEncoder<CdbTelephoneNumberReferenceData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CdbTelephoneNumberReferenceData> DECODER =
      new BinaryMessageDecoder<CdbTelephoneNumberReferenceData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CdbTelephoneNumberReferenceData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CdbTelephoneNumberReferenceData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CdbTelephoneNumberReferenceData>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CdbTelephoneNumberReferenceData to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CdbTelephoneNumberReferenceData from a ByteBuffer. */
  public static CdbTelephoneNumberReferenceData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence telephoneTypeCode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CdbTelephoneNumberReferenceData() {}

  /**
   * All-args constructor.
   * @param telephoneTypeCode The new value for telephoneTypeCode
   */
  public CdbTelephoneNumberReferenceData(java.lang.CharSequence telephoneTypeCode) {
    this.telephoneTypeCode = telephoneTypeCode;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return telephoneTypeCode;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: telephoneTypeCode = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'telephoneTypeCode' field.
   * @return The value of the 'telephoneTypeCode' field.
   */
  public java.lang.CharSequence getTelephoneTypeCode() {
    return telephoneTypeCode;
  }

  /**
   * Sets the value of the 'telephoneTypeCode' field.
   * @param value the value to set.
   */
  public void setTelephoneTypeCode(java.lang.CharSequence value) {
    this.telephoneTypeCode = value;
  }

  /**
   * Creates a new CdbTelephoneNumberReferenceData RecordBuilder.
   * @return A new CdbTelephoneNumberReferenceData RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder newBuilder() {
    return new com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder();
  }

  /**
   * Creates a new CdbTelephoneNumberReferenceData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CdbTelephoneNumberReferenceData RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder newBuilder(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder other) {
    return new com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder(other);
  }

  /**
   * Creates a new CdbTelephoneNumberReferenceData RecordBuilder by copying an existing CdbTelephoneNumberReferenceData instance.
   * @param other The existing instance to copy.
   * @return A new CdbTelephoneNumberReferenceData RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder newBuilder(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData other) {
    return new com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder(other);
  }

  /**
   * RecordBuilder for CdbTelephoneNumberReferenceData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CdbTelephoneNumberReferenceData>
    implements org.apache.avro.data.RecordBuilder<CdbTelephoneNumberReferenceData> {

    private java.lang.CharSequence telephoneTypeCode;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.telephoneTypeCode)) {
        this.telephoneTypeCode = data().deepCopy(fields()[0].schema(), other.telephoneTypeCode);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CdbTelephoneNumberReferenceData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.telephoneTypeCode)) {
        this.telephoneTypeCode = data().deepCopy(fields()[0].schema(), other.telephoneTypeCode);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'telephoneTypeCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getTelephoneTypeCode() {
      return telephoneTypeCode;
    }

    /**
      * Sets the value of the 'telephoneTypeCode' field.
      * @param value The value of 'telephoneTypeCode'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder setTelephoneTypeCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.telephoneTypeCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'telephoneTypeCode' field has been set.
      * @return True if the 'telephoneTypeCode' field has been set, false otherwise.
      */
    public boolean hasTelephoneTypeCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'telephoneTypeCode' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder clearTelephoneTypeCode() {
      telephoneTypeCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CdbTelephoneNumberReferenceData build() {
      try {
        CdbTelephoneNumberReferenceData record = new CdbTelephoneNumberReferenceData();
        record.telephoneTypeCode = fieldSetFlags()[0] ? this.telephoneTypeCode : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CdbTelephoneNumberReferenceData>
    WRITER$ = (org.apache.avro.io.DatumWriter<CdbTelephoneNumberReferenceData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CdbTelephoneNumberReferenceData>
    READER$ = (org.apache.avro.io.DatumReader<CdbTelephoneNumberReferenceData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
