/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uhc.schema.model.eligibility.individual;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** an alternate identifier for the individual */
@org.apache.avro.specific.AvroGenerated
public class AlternateIdentifierValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5237582261879913359L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AlternateIdentifierValue\",\"namespace\":\"com.uhc.schema.model.eligibility.individual\",\"doc\":\"an alternate identifier for the individual\",\"fields\":[{\"name\":\"active\",\"type\":\"boolean\",\"default\":false},{\"name\":\"identifier\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"isPreferredIndicator\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lastUpdated\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"LastUpdated\",\"namespace\":\"com.uhc.schema.model.eligibility.common\",\"doc\":\"Information about the last update made to a given entity.\",\"fields\":[{\"name\":\"sourceSystemTimestamp\",\"type\":[\"null\",\"string\"],\"doc\":\"The last time the entity was updated on the source system (CDB ROW_TMSTMP) in format (UTC timezone): CCYY-MM-DDThh:mm:ss.sssZ\",\"default\":null},{\"name\":\"sourceTimestamp\",\"type\":[\"null\",\"string\"],\"doc\":\"The last time the entity was updated on the originating source (CDB SRC_TMSTMP) in format (UTC timezone): CCYY-MM-DDThh:mm:ss.sssZ\",\"default\":null},{\"name\":\"userId\",\"type\":[\"null\",\"string\"],\"doc\":\"The last person or application to update the entity.\",\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AlternateIdentifierValue> ENCODER =
      new BinaryMessageEncoder<AlternateIdentifierValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AlternateIdentifierValue> DECODER =
      new BinaryMessageDecoder<AlternateIdentifierValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AlternateIdentifierValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AlternateIdentifierValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AlternateIdentifierValue>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AlternateIdentifierValue to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AlternateIdentifierValue from a ByteBuffer. */
  public static AlternateIdentifierValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public boolean active;
  @Deprecated public java.lang.CharSequence identifier;
  @Deprecated public java.lang.CharSequence isPreferredIndicator;
  @Deprecated public com.uhc.schema.model.eligibility.common.LastUpdated lastUpdated;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AlternateIdentifierValue() {}

  /**
   * All-args constructor.
   * @param active The new value for active
   * @param identifier The new value for identifier
   * @param isPreferredIndicator The new value for isPreferredIndicator
   * @param lastUpdated The new value for lastUpdated
   */
  public AlternateIdentifierValue(java.lang.Boolean active, java.lang.CharSequence identifier, java.lang.CharSequence isPreferredIndicator, com.uhc.schema.model.eligibility.common.LastUpdated lastUpdated) {
    this.active = active;
    this.identifier = identifier;
    this.isPreferredIndicator = isPreferredIndicator;
    this.lastUpdated = lastUpdated;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return active;
    case 1: return identifier;
    case 2: return isPreferredIndicator;
    case 3: return lastUpdated;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: active = (java.lang.Boolean)value$; break;
    case 1: identifier = (java.lang.CharSequence)value$; break;
    case 2: isPreferredIndicator = (java.lang.CharSequence)value$; break;
    case 3: lastUpdated = (com.uhc.schema.model.eligibility.common.LastUpdated)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'active' field.
   * @return The value of the 'active' field.
   */
  public java.lang.Boolean getActive() {
    return active;
  }

  /**
   * Sets the value of the 'active' field.
   * @param value the value to set.
   */
  public void setActive(java.lang.Boolean value) {
    this.active = value;
  }

  /**
   * Gets the value of the 'identifier' field.
   * @return The value of the 'identifier' field.
   */
  public java.lang.CharSequence getIdentifier() {
    return identifier;
  }

  /**
   * Sets the value of the 'identifier' field.
   * @param value the value to set.
   */
  public void setIdentifier(java.lang.CharSequence value) {
    this.identifier = value;
  }

  /**
   * Gets the value of the 'isPreferredIndicator' field.
   * @return The value of the 'isPreferredIndicator' field.
   */
  public java.lang.CharSequence getIsPreferredIndicator() {
    return isPreferredIndicator;
  }

  /**
   * Sets the value of the 'isPreferredIndicator' field.
   * @param value the value to set.
   */
  public void setIsPreferredIndicator(java.lang.CharSequence value) {
    this.isPreferredIndicator = value;
  }

  /**
   * Gets the value of the 'lastUpdated' field.
   * @return The value of the 'lastUpdated' field.
   */
  public com.uhc.schema.model.eligibility.common.LastUpdated getLastUpdated() {
    return lastUpdated;
  }

  /**
   * Sets the value of the 'lastUpdated' field.
   * @param value the value to set.
   */
  public void setLastUpdated(com.uhc.schema.model.eligibility.common.LastUpdated value) {
    this.lastUpdated = value;
  }

  /**
   * Creates a new AlternateIdentifierValue RecordBuilder.
   * @return A new AlternateIdentifierValue RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder newBuilder() {
    return new com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder();
  }

  /**
   * Creates a new AlternateIdentifierValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AlternateIdentifierValue RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder newBuilder(com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder other) {
    return new com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder(other);
  }

  /**
   * Creates a new AlternateIdentifierValue RecordBuilder by copying an existing AlternateIdentifierValue instance.
   * @param other The existing instance to copy.
   * @return A new AlternateIdentifierValue RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder newBuilder(com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue other) {
    return new com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder(other);
  }

  /**
   * RecordBuilder for AlternateIdentifierValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AlternateIdentifierValue>
    implements org.apache.avro.data.RecordBuilder<AlternateIdentifierValue> {

    private boolean active;
    private java.lang.CharSequence identifier;
    private java.lang.CharSequence isPreferredIndicator;
    private com.uhc.schema.model.eligibility.common.LastUpdated lastUpdated;
    private com.uhc.schema.model.eligibility.common.LastUpdated.Builder lastUpdatedBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.active)) {
        this.active = data().deepCopy(fields()[0].schema(), other.active);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.identifier)) {
        this.identifier = data().deepCopy(fields()[1].schema(), other.identifier);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.isPreferredIndicator)) {
        this.isPreferredIndicator = data().deepCopy(fields()[2].schema(), other.isPreferredIndicator);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastUpdated)) {
        this.lastUpdated = data().deepCopy(fields()[3].schema(), other.lastUpdated);
        fieldSetFlags()[3] = true;
      }
      if (other.hasLastUpdatedBuilder()) {
        this.lastUpdatedBuilder = com.uhc.schema.model.eligibility.common.LastUpdated.newBuilder(other.getLastUpdatedBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing AlternateIdentifierValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.active)) {
        this.active = data().deepCopy(fields()[0].schema(), other.active);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.identifier)) {
        this.identifier = data().deepCopy(fields()[1].schema(), other.identifier);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.isPreferredIndicator)) {
        this.isPreferredIndicator = data().deepCopy(fields()[2].schema(), other.isPreferredIndicator);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastUpdated)) {
        this.lastUpdated = data().deepCopy(fields()[3].schema(), other.lastUpdated);
        fieldSetFlags()[3] = true;
      }
      this.lastUpdatedBuilder = null;
    }

    /**
      * Gets the value of the 'active' field.
      * @return The value.
      */
    public java.lang.Boolean getActive() {
      return active;
    }

    /**
      * Sets the value of the 'active' field.
      * @param value The value of 'active'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder setActive(boolean value) {
      validate(fields()[0], value);
      this.active = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'active' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder clearActive() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'identifier' field.
      * @return The value.
      */
    public java.lang.CharSequence getIdentifier() {
      return identifier;
    }

    /**
      * Sets the value of the 'identifier' field.
      * @param value The value of 'identifier'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder setIdentifier(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.identifier = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'identifier' field has been set.
      * @return True if the 'identifier' field has been set, false otherwise.
      */
    public boolean hasIdentifier() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'identifier' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder clearIdentifier() {
      identifier = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'isPreferredIndicator' field.
      * @return The value.
      */
    public java.lang.CharSequence getIsPreferredIndicator() {
      return isPreferredIndicator;
    }

    /**
      * Sets the value of the 'isPreferredIndicator' field.
      * @param value The value of 'isPreferredIndicator'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder setIsPreferredIndicator(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.isPreferredIndicator = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'isPreferredIndicator' field has been set.
      * @return True if the 'isPreferredIndicator' field has been set, false otherwise.
      */
    public boolean hasIsPreferredIndicator() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'isPreferredIndicator' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder clearIsPreferredIndicator() {
      isPreferredIndicator = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastUpdated' field.
      * @return The value.
      */
    public com.uhc.schema.model.eligibility.common.LastUpdated getLastUpdated() {
      return lastUpdated;
    }

    /**
      * Sets the value of the 'lastUpdated' field.
      * @param value The value of 'lastUpdated'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder setLastUpdated(com.uhc.schema.model.eligibility.common.LastUpdated value) {
      validate(fields()[3], value);
      this.lastUpdatedBuilder = null;
      this.lastUpdated = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lastUpdated' field has been set.
      * @return True if the 'lastUpdated' field has been set, false otherwise.
      */
    public boolean hasLastUpdated() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'lastUpdated' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.common.LastUpdated.Builder getLastUpdatedBuilder() {
      if (lastUpdatedBuilder == null) {
        if (hasLastUpdated()) {
          setLastUpdatedBuilder(com.uhc.schema.model.eligibility.common.LastUpdated.newBuilder(lastUpdated));
        } else {
          setLastUpdatedBuilder(com.uhc.schema.model.eligibility.common.LastUpdated.newBuilder());
        }
      }
      return lastUpdatedBuilder;
    }

    /**
     * Sets the Builder instance for the 'lastUpdated' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder setLastUpdatedBuilder(com.uhc.schema.model.eligibility.common.LastUpdated.Builder value) {
      clearLastUpdated();
      lastUpdatedBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'lastUpdated' field has an active Builder instance
     * @return True if the 'lastUpdated' field has an active Builder instance
     */
    public boolean hasLastUpdatedBuilder() {
      return lastUpdatedBuilder != null;
    }

    /**
      * Clears the value of the 'lastUpdated' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.AlternateIdentifierValue.Builder clearLastUpdated() {
      lastUpdated = null;
      lastUpdatedBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AlternateIdentifierValue build() {
      try {
        AlternateIdentifierValue record = new AlternateIdentifierValue();
        record.active = fieldSetFlags()[0] ? this.active : (java.lang.Boolean) defaultValue(fields()[0]);
        record.identifier = fieldSetFlags()[1] ? this.identifier : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.isPreferredIndicator = fieldSetFlags()[2] ? this.isPreferredIndicator : (java.lang.CharSequence) defaultValue(fields()[2]);
        if (lastUpdatedBuilder != null) {
          record.lastUpdated = this.lastUpdatedBuilder.build();
        } else {
          record.lastUpdated = fieldSetFlags()[3] ? this.lastUpdated : (com.uhc.schema.model.eligibility.common.LastUpdated) defaultValue(fields()[3]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AlternateIdentifierValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<AlternateIdentifierValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AlternateIdentifierValue>
    READER$ = (org.apache.avro.io.DatumReader<AlternateIdentifierValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
