/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uhc.schema.model.eligibility.individual;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PolicyAmount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -280504489029941269L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PolicyAmount\",\"namespace\":\"com.uhc.schema.model.eligibility.individual\",\"fields\":[{\"name\":\"active\",\"type\":\"boolean\",\"default\":false},{\"name\":\"effectiveDate\",\"type\":[\"null\",\"string\"],\"doc\":\"Date format: CCYY-MM-DD\",\"default\":null},{\"name\":\"policyAmount\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"terminationDate\",\"type\":[\"null\",\"string\"],\"doc\":\"Date format: CCYY-MM-DD\",\"default\":null},{\"name\":\"type\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DescriptionType\",\"namespace\":\"com.uhc.schema.model.eligibility.common\",\"fields\":[{\"name\":\"code\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PolicyAmount> ENCODER =
      new BinaryMessageEncoder<PolicyAmount>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PolicyAmount> DECODER =
      new BinaryMessageDecoder<PolicyAmount>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PolicyAmount> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PolicyAmount> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PolicyAmount>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PolicyAmount to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PolicyAmount from a ByteBuffer. */
  public static PolicyAmount fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public boolean active;
  /** Date format: CCYY-MM-DD */
  @Deprecated public java.lang.CharSequence effectiveDate;
  @Deprecated public java.lang.CharSequence policyAmount;
  /** Date format: CCYY-MM-DD */
  @Deprecated public java.lang.CharSequence terminationDate;
  @Deprecated public com.uhc.schema.model.eligibility.common.DescriptionType type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PolicyAmount() {}

  /**
   * All-args constructor.
   * @param active The new value for active
   * @param effectiveDate Date format: CCYY-MM-DD
   * @param policyAmount The new value for policyAmount
   * @param terminationDate Date format: CCYY-MM-DD
   * @param type The new value for type
   */
  public PolicyAmount(java.lang.Boolean active, java.lang.CharSequence effectiveDate, java.lang.CharSequence policyAmount, java.lang.CharSequence terminationDate, com.uhc.schema.model.eligibility.common.DescriptionType type) {
    this.active = active;
    this.effectiveDate = effectiveDate;
    this.policyAmount = policyAmount;
    this.terminationDate = terminationDate;
    this.type = type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return active;
    case 1: return effectiveDate;
    case 2: return policyAmount;
    case 3: return terminationDate;
    case 4: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: active = (java.lang.Boolean)value$; break;
    case 1: effectiveDate = (java.lang.CharSequence)value$; break;
    case 2: policyAmount = (java.lang.CharSequence)value$; break;
    case 3: terminationDate = (java.lang.CharSequence)value$; break;
    case 4: type = (com.uhc.schema.model.eligibility.common.DescriptionType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'active' field.
   * @return The value of the 'active' field.
   */
  public java.lang.Boolean getActive() {
    return active;
  }

  /**
   * Sets the value of the 'active' field.
   * @param value the value to set.
   */
  public void setActive(java.lang.Boolean value) {
    this.active = value;
  }

  /**
   * Gets the value of the 'effectiveDate' field.
   * @return Date format: CCYY-MM-DD
   */
  public java.lang.CharSequence getEffectiveDate() {
    return effectiveDate;
  }

  /**
   * Sets the value of the 'effectiveDate' field.
   * Date format: CCYY-MM-DD
   * @param value the value to set.
   */
  public void setEffectiveDate(java.lang.CharSequence value) {
    this.effectiveDate = value;
  }

  /**
   * Gets the value of the 'policyAmount' field.
   * @return The value of the 'policyAmount' field.
   */
  public java.lang.CharSequence getPolicyAmount() {
    return policyAmount;
  }

  /**
   * Sets the value of the 'policyAmount' field.
   * @param value the value to set.
   */
  public void setPolicyAmount(java.lang.CharSequence value) {
    this.policyAmount = value;
  }

  /**
   * Gets the value of the 'terminationDate' field.
   * @return Date format: CCYY-MM-DD
   */
  public java.lang.CharSequence getTerminationDate() {
    return terminationDate;
  }

  /**
   * Sets the value of the 'terminationDate' field.
   * Date format: CCYY-MM-DD
   * @param value the value to set.
   */
  public void setTerminationDate(java.lang.CharSequence value) {
    this.terminationDate = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public com.uhc.schema.model.eligibility.common.DescriptionType getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(com.uhc.schema.model.eligibility.common.DescriptionType value) {
    this.type = value;
  }

  /**
   * Creates a new PolicyAmount RecordBuilder.
   * @return A new PolicyAmount RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder newBuilder() {
    return new com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder();
  }

  /**
   * Creates a new PolicyAmount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PolicyAmount RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder newBuilder(com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder other) {
    return new com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder(other);
  }

  /**
   * Creates a new PolicyAmount RecordBuilder by copying an existing PolicyAmount instance.
   * @param other The existing instance to copy.
   * @return A new PolicyAmount RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder newBuilder(com.uhc.schema.model.eligibility.individual.PolicyAmount other) {
    return new com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder(other);
  }

  /**
   * RecordBuilder for PolicyAmount instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PolicyAmount>
    implements org.apache.avro.data.RecordBuilder<PolicyAmount> {

    private boolean active;
    /** Date format: CCYY-MM-DD */
    private java.lang.CharSequence effectiveDate;
    private java.lang.CharSequence policyAmount;
    /** Date format: CCYY-MM-DD */
    private java.lang.CharSequence terminationDate;
    private com.uhc.schema.model.eligibility.common.DescriptionType type;
    private com.uhc.schema.model.eligibility.common.DescriptionType.Builder typeBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.active)) {
        this.active = data().deepCopy(fields()[0].schema(), other.active);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.effectiveDate)) {
        this.effectiveDate = data().deepCopy(fields()[1].schema(), other.effectiveDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.policyAmount)) {
        this.policyAmount = data().deepCopy(fields()[2].schema(), other.policyAmount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.terminationDate)) {
        this.terminationDate = data().deepCopy(fields()[3].schema(), other.terminationDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.type)) {
        this.type = data().deepCopy(fields()[4].schema(), other.type);
        fieldSetFlags()[4] = true;
      }
      if (other.hasTypeBuilder()) {
        this.typeBuilder = com.uhc.schema.model.eligibility.common.DescriptionType.newBuilder(other.getTypeBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing PolicyAmount instance
     * @param other The existing instance to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.individual.PolicyAmount other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.active)) {
        this.active = data().deepCopy(fields()[0].schema(), other.active);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.effectiveDate)) {
        this.effectiveDate = data().deepCopy(fields()[1].schema(), other.effectiveDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.policyAmount)) {
        this.policyAmount = data().deepCopy(fields()[2].schema(), other.policyAmount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.terminationDate)) {
        this.terminationDate = data().deepCopy(fields()[3].schema(), other.terminationDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.type)) {
        this.type = data().deepCopy(fields()[4].schema(), other.type);
        fieldSetFlags()[4] = true;
      }
      this.typeBuilder = null;
    }

    /**
      * Gets the value of the 'active' field.
      * @return The value.
      */
    public java.lang.Boolean getActive() {
      return active;
    }

    /**
      * Sets the value of the 'active' field.
      * @param value The value of 'active'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder setActive(boolean value) {
      validate(fields()[0], value);
      this.active = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'active' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder clearActive() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'effectiveDate' field.
      * Date format: CCYY-MM-DD
      * @return The value.
      */
    public java.lang.CharSequence getEffectiveDate() {
      return effectiveDate;
    }

    /**
      * Sets the value of the 'effectiveDate' field.
      * Date format: CCYY-MM-DD
      * @param value The value of 'effectiveDate'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder setEffectiveDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.effectiveDate = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'effectiveDate' field has been set.
      * Date format: CCYY-MM-DD
      * @return True if the 'effectiveDate' field has been set, false otherwise.
      */
    public boolean hasEffectiveDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'effectiveDate' field.
      * Date format: CCYY-MM-DD
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder clearEffectiveDate() {
      effectiveDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'policyAmount' field.
      * @return The value.
      */
    public java.lang.CharSequence getPolicyAmount() {
      return policyAmount;
    }

    /**
      * Sets the value of the 'policyAmount' field.
      * @param value The value of 'policyAmount'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder setPolicyAmount(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.policyAmount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'policyAmount' field has been set.
      * @return True if the 'policyAmount' field has been set, false otherwise.
      */
    public boolean hasPolicyAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'policyAmount' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder clearPolicyAmount() {
      policyAmount = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'terminationDate' field.
      * Date format: CCYY-MM-DD
      * @return The value.
      */
    public java.lang.CharSequence getTerminationDate() {
      return terminationDate;
    }

    /**
      * Sets the value of the 'terminationDate' field.
      * Date format: CCYY-MM-DD
      * @param value The value of 'terminationDate'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder setTerminationDate(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.terminationDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'terminationDate' field has been set.
      * Date format: CCYY-MM-DD
      * @return True if the 'terminationDate' field has been set, false otherwise.
      */
    public boolean hasTerminationDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'terminationDate' field.
      * Date format: CCYY-MM-DD
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder clearTerminationDate() {
      terminationDate = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public com.uhc.schema.model.eligibility.common.DescriptionType getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder setType(com.uhc.schema.model.eligibility.common.DescriptionType value) {
      validate(fields()[4], value);
      this.typeBuilder = null;
      this.type = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'type' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.common.DescriptionType.Builder getTypeBuilder() {
      if (typeBuilder == null) {
        if (hasType()) {
          setTypeBuilder(com.uhc.schema.model.eligibility.common.DescriptionType.newBuilder(type));
        } else {
          setTypeBuilder(com.uhc.schema.model.eligibility.common.DescriptionType.newBuilder());
        }
      }
      return typeBuilder;
    }

    /**
     * Sets the Builder instance for the 'type' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder setTypeBuilder(com.uhc.schema.model.eligibility.common.DescriptionType.Builder value) {
      clearType();
      typeBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'type' field has an active Builder instance
     * @return True if the 'type' field has an active Builder instance
     */
    public boolean hasTypeBuilder() {
      return typeBuilder != null;
    }

    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.PolicyAmount.Builder clearType() {
      type = null;
      typeBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PolicyAmount build() {
      try {
        PolicyAmount record = new PolicyAmount();
        record.active = fieldSetFlags()[0] ? this.active : (java.lang.Boolean) defaultValue(fields()[0]);
        record.effectiveDate = fieldSetFlags()[1] ? this.effectiveDate : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.policyAmount = fieldSetFlags()[2] ? this.policyAmount : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.terminationDate = fieldSetFlags()[3] ? this.terminationDate : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (typeBuilder != null) {
          record.type = this.typeBuilder.build();
        } else {
          record.type = fieldSetFlags()[4] ? this.type : (com.uhc.schema.model.eligibility.common.DescriptionType) defaultValue(fields()[4]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PolicyAmount>
    WRITER$ = (org.apache.avro.io.DatumWriter<PolicyAmount>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PolicyAmount>
    READER$ = (org.apache.avro.io.DatumReader<PolicyAmount>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
