/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uhc.schema.model.eligibility.individual;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TelephoneNumberSourceSystemAttributes extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3775838060474413557L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TelephoneNumberSourceSystemAttributes\",\"namespace\":\"com.uhc.schema.model.eligibility.individual\",\"fields\":[{\"name\":\"cdb\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"CdbTelephoneNumberReferenceData\",\"namespace\":\"com.uhc.schema.model.eligibility.cdb\",\"fields\":[{\"name\":\"telephoneTypeCode\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TelephoneNumberSourceSystemAttributes> ENCODER =
      new BinaryMessageEncoder<TelephoneNumberSourceSystemAttributes>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TelephoneNumberSourceSystemAttributes> DECODER =
      new BinaryMessageDecoder<TelephoneNumberSourceSystemAttributes>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TelephoneNumberSourceSystemAttributes> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TelephoneNumberSourceSystemAttributes> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TelephoneNumberSourceSystemAttributes>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TelephoneNumberSourceSystemAttributes to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TelephoneNumberSourceSystemAttributes from a ByteBuffer. */
  public static TelephoneNumberSourceSystemAttributes fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData cdb;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TelephoneNumberSourceSystemAttributes() {}

  /**
   * All-args constructor.
   * @param cdb The new value for cdb
   */
  public TelephoneNumberSourceSystemAttributes(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData cdb) {
    this.cdb = cdb;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cdb;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cdb = (com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'cdb' field.
   * @return The value of the 'cdb' field.
   */
  public com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData getCdb() {
    return cdb;
  }

  /**
   * Sets the value of the 'cdb' field.
   * @param value the value to set.
   */
  public void setCdb(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData value) {
    this.cdb = value;
  }

  /**
   * Creates a new TelephoneNumberSourceSystemAttributes RecordBuilder.
   * @return A new TelephoneNumberSourceSystemAttributes RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder newBuilder() {
    return new com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder();
  }

  /**
   * Creates a new TelephoneNumberSourceSystemAttributes RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TelephoneNumberSourceSystemAttributes RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder newBuilder(com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder other) {
    return new com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder(other);
  }

  /**
   * Creates a new TelephoneNumberSourceSystemAttributes RecordBuilder by copying an existing TelephoneNumberSourceSystemAttributes instance.
   * @param other The existing instance to copy.
   * @return A new TelephoneNumberSourceSystemAttributes RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder newBuilder(com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes other) {
    return new com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder(other);
  }

  /**
   * RecordBuilder for TelephoneNumberSourceSystemAttributes instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TelephoneNumberSourceSystemAttributes>
    implements org.apache.avro.data.RecordBuilder<TelephoneNumberSourceSystemAttributes> {

    private com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData cdb;
    private com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder cdbBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cdb)) {
        this.cdb = data().deepCopy(fields()[0].schema(), other.cdb);
        fieldSetFlags()[0] = true;
      }
      if (other.hasCdbBuilder()) {
        this.cdbBuilder = com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.newBuilder(other.getCdbBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing TelephoneNumberSourceSystemAttributes instance
     * @param other The existing instance to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.cdb)) {
        this.cdb = data().deepCopy(fields()[0].schema(), other.cdb);
        fieldSetFlags()[0] = true;
      }
      this.cdbBuilder = null;
    }

    /**
      * Gets the value of the 'cdb' field.
      * @return The value.
      */
    public com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData getCdb() {
      return cdb;
    }

    /**
      * Sets the value of the 'cdb' field.
      * @param value The value of 'cdb'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder setCdb(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData value) {
      validate(fields()[0], value);
      this.cdbBuilder = null;
      this.cdb = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cdb' field has been set.
      * @return True if the 'cdb' field has been set, false otherwise.
      */
    public boolean hasCdb() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'cdb' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder getCdbBuilder() {
      if (cdbBuilder == null) {
        if (hasCdb()) {
          setCdbBuilder(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.newBuilder(cdb));
        } else {
          setCdbBuilder(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.newBuilder());
        }
      }
      return cdbBuilder;
    }

    /**
     * Sets the Builder instance for the 'cdb' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder setCdbBuilder(com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData.Builder value) {
      clearCdb();
      cdbBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'cdb' field has an active Builder instance
     * @return True if the 'cdb' field has an active Builder instance
     */
    public boolean hasCdbBuilder() {
      return cdbBuilder != null;
    }

    /**
      * Clears the value of the 'cdb' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.individual.TelephoneNumberSourceSystemAttributes.Builder clearCdb() {
      cdb = null;
      cdbBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TelephoneNumberSourceSystemAttributes build() {
      try {
        TelephoneNumberSourceSystemAttributes record = new TelephoneNumberSourceSystemAttributes();
        if (cdbBuilder != null) {
          record.cdb = this.cdbBuilder.build();
        } else {
          record.cdb = fieldSetFlags()[0] ? this.cdb : (com.uhc.schema.model.eligibility.cdb.CdbTelephoneNumberReferenceData) defaultValue(fields()[0]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TelephoneNumberSourceSystemAttributes>
    WRITER$ = (org.apache.avro.io.DatumWriter<TelephoneNumberSourceSystemAttributes>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TelephoneNumberSourceSystemAttributes>
    READER$ = (org.apache.avro.io.DatumReader<TelephoneNumberSourceSystemAttributes>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
