/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uhc.schema.model.eligibility.membership;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MemberDeliveryPreference extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5236444069898789832L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MemberDeliveryPreference\",\"namespace\":\"com.uhc.schema.model.eligibility.membership\",\"fields\":[{\"name\":\"deliveryType\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DescriptionType\",\"namespace\":\"com.uhc.schema.model.eligibility.common\",\"fields\":[{\"name\":\"code\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null},{\"name\":\"fulfillmentIdentifier\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lastModifiedDate\",\"type\":[\"null\",\"string\"],\"doc\":\"Date Member Delivery Preference was modified. Date format: CCYY-MM-DD\",\"default\":null},{\"name\":\"lastModifiedUser\",\"type\":[\"null\",\"string\"],\"doc\":\"User name of the user modifying Member Delivery Preference.\",\"default\":null},{\"name\":\"preferenceDates\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DateRangeType\",\"namespace\":\"com.uhc.schema.model.eligibility.common\",\"fields\":[{\"name\":\"startDate\",\"type\":[\"null\",\"string\"],\"doc\":\"Date format: CCYY-MM-DD\",\"default\":null},{\"name\":\"endDate\",\"type\":[\"null\",\"string\"],\"doc\":\"Date format: CCYY-MM-DD\",\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MemberDeliveryPreference> ENCODER =
      new BinaryMessageEncoder<MemberDeliveryPreference>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MemberDeliveryPreference> DECODER =
      new BinaryMessageDecoder<MemberDeliveryPreference>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MemberDeliveryPreference> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MemberDeliveryPreference> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MemberDeliveryPreference>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MemberDeliveryPreference to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MemberDeliveryPreference from a ByteBuffer. */
  public static MemberDeliveryPreference fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public com.uhc.schema.model.eligibility.common.DescriptionType deliveryType;
  @Deprecated public java.lang.CharSequence fulfillmentIdentifier;
  /** Date Member Delivery Preference was modified. Date format: CCYY-MM-DD */
  @Deprecated public java.lang.CharSequence lastModifiedDate;
  /** User name of the user modifying Member Delivery Preference. */
  @Deprecated public java.lang.CharSequence lastModifiedUser;
  @Deprecated public com.uhc.schema.model.eligibility.common.DateRangeType preferenceDates;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MemberDeliveryPreference() {}

  /**
   * All-args constructor.
   * @param deliveryType The new value for deliveryType
   * @param fulfillmentIdentifier The new value for fulfillmentIdentifier
   * @param lastModifiedDate Date Member Delivery Preference was modified. Date format: CCYY-MM-DD
   * @param lastModifiedUser User name of the user modifying Member Delivery Preference.
   * @param preferenceDates The new value for preferenceDates
   */
  public MemberDeliveryPreference(com.uhc.schema.model.eligibility.common.DescriptionType deliveryType, java.lang.CharSequence fulfillmentIdentifier, java.lang.CharSequence lastModifiedDate, java.lang.CharSequence lastModifiedUser, com.uhc.schema.model.eligibility.common.DateRangeType preferenceDates) {
    this.deliveryType = deliveryType;
    this.fulfillmentIdentifier = fulfillmentIdentifier;
    this.lastModifiedDate = lastModifiedDate;
    this.lastModifiedUser = lastModifiedUser;
    this.preferenceDates = preferenceDates;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deliveryType;
    case 1: return fulfillmentIdentifier;
    case 2: return lastModifiedDate;
    case 3: return lastModifiedUser;
    case 4: return preferenceDates;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deliveryType = (com.uhc.schema.model.eligibility.common.DescriptionType)value$; break;
    case 1: fulfillmentIdentifier = (java.lang.CharSequence)value$; break;
    case 2: lastModifiedDate = (java.lang.CharSequence)value$; break;
    case 3: lastModifiedUser = (java.lang.CharSequence)value$; break;
    case 4: preferenceDates = (com.uhc.schema.model.eligibility.common.DateRangeType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'deliveryType' field.
   * @return The value of the 'deliveryType' field.
   */
  public com.uhc.schema.model.eligibility.common.DescriptionType getDeliveryType() {
    return deliveryType;
  }

  /**
   * Sets the value of the 'deliveryType' field.
   * @param value the value to set.
   */
  public void setDeliveryType(com.uhc.schema.model.eligibility.common.DescriptionType value) {
    this.deliveryType = value;
  }

  /**
   * Gets the value of the 'fulfillmentIdentifier' field.
   * @return The value of the 'fulfillmentIdentifier' field.
   */
  public java.lang.CharSequence getFulfillmentIdentifier() {
    return fulfillmentIdentifier;
  }

  /**
   * Sets the value of the 'fulfillmentIdentifier' field.
   * @param value the value to set.
   */
  public void setFulfillmentIdentifier(java.lang.CharSequence value) {
    this.fulfillmentIdentifier = value;
  }

  /**
   * Gets the value of the 'lastModifiedDate' field.
   * @return Date Member Delivery Preference was modified. Date format: CCYY-MM-DD
   */
  public java.lang.CharSequence getLastModifiedDate() {
    return lastModifiedDate;
  }

  /**
   * Sets the value of the 'lastModifiedDate' field.
   * Date Member Delivery Preference was modified. Date format: CCYY-MM-DD
   * @param value the value to set.
   */
  public void setLastModifiedDate(java.lang.CharSequence value) {
    this.lastModifiedDate = value;
  }

  /**
   * Gets the value of the 'lastModifiedUser' field.
   * @return User name of the user modifying Member Delivery Preference.
   */
  public java.lang.CharSequence getLastModifiedUser() {
    return lastModifiedUser;
  }

  /**
   * Sets the value of the 'lastModifiedUser' field.
   * User name of the user modifying Member Delivery Preference.
   * @param value the value to set.
   */
  public void setLastModifiedUser(java.lang.CharSequence value) {
    this.lastModifiedUser = value;
  }

  /**
   * Gets the value of the 'preferenceDates' field.
   * @return The value of the 'preferenceDates' field.
   */
  public com.uhc.schema.model.eligibility.common.DateRangeType getPreferenceDates() {
    return preferenceDates;
  }

  /**
   * Sets the value of the 'preferenceDates' field.
   * @param value the value to set.
   */
  public void setPreferenceDates(com.uhc.schema.model.eligibility.common.DateRangeType value) {
    this.preferenceDates = value;
  }

  /**
   * Creates a new MemberDeliveryPreference RecordBuilder.
   * @return A new MemberDeliveryPreference RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder newBuilder() {
    return new com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder();
  }

  /**
   * Creates a new MemberDeliveryPreference RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MemberDeliveryPreference RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder newBuilder(com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder other) {
    return new com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder(other);
  }

  /**
   * Creates a new MemberDeliveryPreference RecordBuilder by copying an existing MemberDeliveryPreference instance.
   * @param other The existing instance to copy.
   * @return A new MemberDeliveryPreference RecordBuilder
   */
  public static com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder newBuilder(com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference other) {
    return new com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder(other);
  }

  /**
   * RecordBuilder for MemberDeliveryPreference instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MemberDeliveryPreference>
    implements org.apache.avro.data.RecordBuilder<MemberDeliveryPreference> {

    private com.uhc.schema.model.eligibility.common.DescriptionType deliveryType;
    private com.uhc.schema.model.eligibility.common.DescriptionType.Builder deliveryTypeBuilder;
    private java.lang.CharSequence fulfillmentIdentifier;
    /** Date Member Delivery Preference was modified. Date format: CCYY-MM-DD */
    private java.lang.CharSequence lastModifiedDate;
    /** User name of the user modifying Member Delivery Preference. */
    private java.lang.CharSequence lastModifiedUser;
    private com.uhc.schema.model.eligibility.common.DateRangeType preferenceDates;
    private com.uhc.schema.model.eligibility.common.DateRangeType.Builder preferenceDatesBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deliveryType)) {
        this.deliveryType = data().deepCopy(fields()[0].schema(), other.deliveryType);
        fieldSetFlags()[0] = true;
      }
      if (other.hasDeliveryTypeBuilder()) {
        this.deliveryTypeBuilder = com.uhc.schema.model.eligibility.common.DescriptionType.newBuilder(other.getDeliveryTypeBuilder());
      }
      if (isValidValue(fields()[1], other.fulfillmentIdentifier)) {
        this.fulfillmentIdentifier = data().deepCopy(fields()[1].schema(), other.fulfillmentIdentifier);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastModifiedDate)) {
        this.lastModifiedDate = data().deepCopy(fields()[2].schema(), other.lastModifiedDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastModifiedUser)) {
        this.lastModifiedUser = data().deepCopy(fields()[3].schema(), other.lastModifiedUser);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.preferenceDates)) {
        this.preferenceDates = data().deepCopy(fields()[4].schema(), other.preferenceDates);
        fieldSetFlags()[4] = true;
      }
      if (other.hasPreferenceDatesBuilder()) {
        this.preferenceDatesBuilder = com.uhc.schema.model.eligibility.common.DateRangeType.newBuilder(other.getPreferenceDatesBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing MemberDeliveryPreference instance
     * @param other The existing instance to copy.
     */
    private Builder(com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.deliveryType)) {
        this.deliveryType = data().deepCopy(fields()[0].schema(), other.deliveryType);
        fieldSetFlags()[0] = true;
      }
      this.deliveryTypeBuilder = null;
      if (isValidValue(fields()[1], other.fulfillmentIdentifier)) {
        this.fulfillmentIdentifier = data().deepCopy(fields()[1].schema(), other.fulfillmentIdentifier);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastModifiedDate)) {
        this.lastModifiedDate = data().deepCopy(fields()[2].schema(), other.lastModifiedDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.lastModifiedUser)) {
        this.lastModifiedUser = data().deepCopy(fields()[3].schema(), other.lastModifiedUser);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.preferenceDates)) {
        this.preferenceDates = data().deepCopy(fields()[4].schema(), other.preferenceDates);
        fieldSetFlags()[4] = true;
      }
      this.preferenceDatesBuilder = null;
    }

    /**
      * Gets the value of the 'deliveryType' field.
      * @return The value.
      */
    public com.uhc.schema.model.eligibility.common.DescriptionType getDeliveryType() {
      return deliveryType;
    }

    /**
      * Sets the value of the 'deliveryType' field.
      * @param value The value of 'deliveryType'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder setDeliveryType(com.uhc.schema.model.eligibility.common.DescriptionType value) {
      validate(fields()[0], value);
      this.deliveryTypeBuilder = null;
      this.deliveryType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deliveryType' field has been set.
      * @return True if the 'deliveryType' field has been set, false otherwise.
      */
    public boolean hasDeliveryType() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'deliveryType' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.common.DescriptionType.Builder getDeliveryTypeBuilder() {
      if (deliveryTypeBuilder == null) {
        if (hasDeliveryType()) {
          setDeliveryTypeBuilder(com.uhc.schema.model.eligibility.common.DescriptionType.newBuilder(deliveryType));
        } else {
          setDeliveryTypeBuilder(com.uhc.schema.model.eligibility.common.DescriptionType.newBuilder());
        }
      }
      return deliveryTypeBuilder;
    }

    /**
     * Sets the Builder instance for the 'deliveryType' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder setDeliveryTypeBuilder(com.uhc.schema.model.eligibility.common.DescriptionType.Builder value) {
      clearDeliveryType();
      deliveryTypeBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'deliveryType' field has an active Builder instance
     * @return True if the 'deliveryType' field has an active Builder instance
     */
    public boolean hasDeliveryTypeBuilder() {
      return deliveryTypeBuilder != null;
    }

    /**
      * Clears the value of the 'deliveryType' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder clearDeliveryType() {
      deliveryType = null;
      deliveryTypeBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fulfillmentIdentifier' field.
      * @return The value.
      */
    public java.lang.CharSequence getFulfillmentIdentifier() {
      return fulfillmentIdentifier;
    }

    /**
      * Sets the value of the 'fulfillmentIdentifier' field.
      * @param value The value of 'fulfillmentIdentifier'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder setFulfillmentIdentifier(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.fulfillmentIdentifier = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fulfillmentIdentifier' field has been set.
      * @return True if the 'fulfillmentIdentifier' field has been set, false otherwise.
      */
    public boolean hasFulfillmentIdentifier() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fulfillmentIdentifier' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder clearFulfillmentIdentifier() {
      fulfillmentIdentifier = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastModifiedDate' field.
      * Date Member Delivery Preference was modified. Date format: CCYY-MM-DD
      * @return The value.
      */
    public java.lang.CharSequence getLastModifiedDate() {
      return lastModifiedDate;
    }

    /**
      * Sets the value of the 'lastModifiedDate' field.
      * Date Member Delivery Preference was modified. Date format: CCYY-MM-DD
      * @param value The value of 'lastModifiedDate'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder setLastModifiedDate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastModifiedDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastModifiedDate' field has been set.
      * Date Member Delivery Preference was modified. Date format: CCYY-MM-DD
      * @return True if the 'lastModifiedDate' field has been set, false otherwise.
      */
    public boolean hasLastModifiedDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastModifiedDate' field.
      * Date Member Delivery Preference was modified. Date format: CCYY-MM-DD
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder clearLastModifiedDate() {
      lastModifiedDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastModifiedUser' field.
      * User name of the user modifying Member Delivery Preference.
      * @return The value.
      */
    public java.lang.CharSequence getLastModifiedUser() {
      return lastModifiedUser;
    }

    /**
      * Sets the value of the 'lastModifiedUser' field.
      * User name of the user modifying Member Delivery Preference.
      * @param value The value of 'lastModifiedUser'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder setLastModifiedUser(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.lastModifiedUser = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'lastModifiedUser' field has been set.
      * User name of the user modifying Member Delivery Preference.
      * @return True if the 'lastModifiedUser' field has been set, false otherwise.
      */
    public boolean hasLastModifiedUser() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'lastModifiedUser' field.
      * User name of the user modifying Member Delivery Preference.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder clearLastModifiedUser() {
      lastModifiedUser = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'preferenceDates' field.
      * @return The value.
      */
    public com.uhc.schema.model.eligibility.common.DateRangeType getPreferenceDates() {
      return preferenceDates;
    }

    /**
      * Sets the value of the 'preferenceDates' field.
      * @param value The value of 'preferenceDates'.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder setPreferenceDates(com.uhc.schema.model.eligibility.common.DateRangeType value) {
      validate(fields()[4], value);
      this.preferenceDatesBuilder = null;
      this.preferenceDates = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'preferenceDates' field has been set.
      * @return True if the 'preferenceDates' field has been set, false otherwise.
      */
    public boolean hasPreferenceDates() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'preferenceDates' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.common.DateRangeType.Builder getPreferenceDatesBuilder() {
      if (preferenceDatesBuilder == null) {
        if (hasPreferenceDates()) {
          setPreferenceDatesBuilder(com.uhc.schema.model.eligibility.common.DateRangeType.newBuilder(preferenceDates));
        } else {
          setPreferenceDatesBuilder(com.uhc.schema.model.eligibility.common.DateRangeType.newBuilder());
        }
      }
      return preferenceDatesBuilder;
    }

    /**
     * Sets the Builder instance for the 'preferenceDates' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder setPreferenceDatesBuilder(com.uhc.schema.model.eligibility.common.DateRangeType.Builder value) {
      clearPreferenceDates();
      preferenceDatesBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'preferenceDates' field has an active Builder instance
     * @return True if the 'preferenceDates' field has an active Builder instance
     */
    public boolean hasPreferenceDatesBuilder() {
      return preferenceDatesBuilder != null;
    }

    /**
      * Clears the value of the 'preferenceDates' field.
      * @return This builder.
      */
    public com.uhc.schema.model.eligibility.membership.MemberDeliveryPreference.Builder clearPreferenceDates() {
      preferenceDates = null;
      preferenceDatesBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MemberDeliveryPreference build() {
      try {
        MemberDeliveryPreference record = new MemberDeliveryPreference();
        if (deliveryTypeBuilder != null) {
          record.deliveryType = this.deliveryTypeBuilder.build();
        } else {
          record.deliveryType = fieldSetFlags()[0] ? this.deliveryType : (com.uhc.schema.model.eligibility.common.DescriptionType) defaultValue(fields()[0]);
        }
        record.fulfillmentIdentifier = fieldSetFlags()[1] ? this.fulfillmentIdentifier : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastModifiedDate = fieldSetFlags()[2] ? this.lastModifiedDate : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.lastModifiedUser = fieldSetFlags()[3] ? this.lastModifiedUser : (java.lang.CharSequence) defaultValue(fields()[3]);
        if (preferenceDatesBuilder != null) {
          record.preferenceDates = this.preferenceDatesBuilder.build();
        } else {
          record.preferenceDates = fieldSetFlags()[4] ? this.preferenceDates : (com.uhc.schema.model.eligibility.common.DateRangeType) defaultValue(fields()[4]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MemberDeliveryPreference>
    WRITER$ = (org.apache.avro.io.DatumWriter<MemberDeliveryPreference>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MemberDeliveryPreference>
    READER$ = (org.apache.avro.io.DatumReader<MemberDeliveryPreference>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
